a=10
print(type(a))
b=10.3
print(type(b))
c=complex(3,4)
print(type(c))                                               
print(type(b))
c=complex(3,4)
print(type(c))

list=[1,2,3,4,5]
print(type(list))
tuple=(1,2,3.34,45)
print(type(tuple))
set={1,3.4,"male",'a'}
print(type(set))
dictionary={"a":"geetha","b":"kumar","c":"vijay","d":"abhi"}
print(type(dictionary))
bl=True
print(type(bl))
list=[1,2,3,4,5]
print(type(list))
tuple=(1,2,3.34,45)
print(type(tuple))
set={1,3.4,"male",'a'}
print(type(set))
dictionary={"a":"geetha","b":"kumar","c":"vijay","d":"abhi"}
print(type(dictionary))
st="geetha"
print(type(st))